### PR TITLE
Fixed bug

### PR DESCRIPTION
**Pull request by Rotendahl**
This fixes the bug introduced in the last pull request. 

Sorry for the late reply I've been super busy. 

The bug was that the docker container didn't contain the "file" command. 

I don't know of a good way to test actions.
If you have any suggestions please let me know.

### CODE REVIEW

**Comment by Rotendahl** [comment]
Fixes #2

**Comment by erclu** [comment]
> I don't know of a good way to test actions.
> If you have any suggestions please let me know.

Yeah i have no idea about how to test bash scripts. I was kinda working on it here: 

https://github.com/erclu/check-crlf/blob/80bfd1668204eddbd2865ae7e9acfa6b15ef1aca/test.sh#L1-L18

The idea was to create on-the-fly the files to be tested and manually invoke the `entrypoint.sh` script inside a GitHub action (found [here](https://github.com/erclu/check-crlf/blob/master/.github/workflows/test.yml)). Kinda unconventional but it should do.

BTW if you rebase/merge on the master branch i've just pushed you'd probably trigger the workflow check.

**Comment by jmckenna** [comment]
Thanks Rotendahl !       I'm assuming that I should use the v2 tag to test this now?

**Comment by erclu** [comment]
@jmckenna I've cleaned up some stuff and merged this PR. I suppose it will work but i'll wait for you to test it before moving the `v1` tag.
You can target explicitly the various versions i've published, the most recent (which contains the fix applied by this PR) can be used by specifying 

```yaml
...
      - uses: erclu/check-crlf@v1.1.1
...
```

let me know how it goes!

**Comment by jmckenna** [comment]
@erclu tested v1.1.1     The output with exclude is:

```
searching for CRLF endings in: .
\033[1;32mNo files with CRLF endings found.\033[0m
```

It works, but the "\033" in then message looks odd.

**Comment by Rotendahl** [comment]
The `\033` was an attempt to get colors in the output. I would show a green color on success on a red color on failure. 
It seems that GitHub has changed the way they add colors to actions https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/

**Comment by jmckenna** [comment]
thanks @Rotendahl, it seems the ANSI color syntax did not work, I am not sure why.

**Comment by jmckenna** [comment]
the ANSI colors do work with v1.0.0 (tested again now).  So this problem only applies to v1.1.1

**Comment by Rotendahl** [comment]
@jmckenna do you mind testing the new version?

**Comment by jmckenna** [comment]
1.1.2 works well!    (color issue is fixed, exclude working)  thanks!

**Comment by Rotendahl** [comment]
Thanks!

**Pull request merged**
